feat(24.10): add SDF for file and dependecies

diff --git a/tests/spread/integration/file/task.yaml b/tests/spread/integration/file/task.yaml
--- a/tests/spread/integration/file/task.yaml
+++ b/tests/spread/integration/file/task.yaml
@@ -4,3 +4,10 @@ execute: |
   rootfs="$(install-slices file_bins)"
 
   chroot "${rootfs}/" file --help
+  echo "Hello World" > "${rootfs}/testfile" 
+  output=$(chroot "${rootfs}/" \
+    file -b testfile)
+  if [ "$output" != "ASCII text" ]; then 
+    echo "file failed"
+    exit 1
+  fi
